# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# set workdir
WORKDIR /app

# install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc

# copy project files
COPY . /app

# install python dependencies
RUN pip install --upgrade pip && pip install .

# expose port if needed (optional)
# EXPOSE 8000

# start the MCP server
CMD ["figma-mcp", "--figma-api-key=your_figma_api_key"]
